version: '3'

services:
  mtrk8demo:
    image: mtrk8demo:dev
    build:
      args:
        source: obj/Docker/empty/
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - c:\users\samslee\documents\visual studio 2017\Projects\mtrK8demo\mtrK8demo:/app
      - C:\Users\samslee\vsdbg:/remote_debugger:ro
      - C:\Users\samslee\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Users\samslee\.nuget\packages\:/root/.nuget/fallbackpackages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp1.1/mtrK8demo.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
